name: flutter_sanity_plus
description: Dart libary to query the Sanity.io API. Supports running queries and downloading files.
version: 2.0.0+1
homepage: https://github.com/devaryakjha/flutter-sanity
repository: https://github.com/devaryakjha/flutter-sanity

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  http: ^1.2.1

dev_dependencies:
  test: ^1.25.4
